name: "ghas-seat-projection"
description: "Projection of the number GHAS licences that will be used"
inputs:
  organization:
    description: Organization to be checked
    required: true
  repository:
    description: Repository to be checked, exclude public repositories
    required: true
  authentication:
    description: Authentication method, either 'app' or 'token'
    required: true
  token:
    description: PAT
    required: false
  application-id:
    description: Application ID of GitHub App, used if `authentication` is set to 'app'
    required: false
  application-private-key:
    description: Private SSH key of GitHub App, used if `authentication` is set to 'app'
    required: false
  installation-id:
    description: Installation ID of GitHub App, used if `authentication` is set to 'app'
    required: false
outputs:
  ghas-seats:
    description: Number of GHAS licences that will be activated
  ghas-handles:
    description: Array containing all GitHub Handles of the users that will consume a GHAS licence
runs:
  using: "node20"
  main: "index.js"